### ISSUE TITLE
Error running tests with Django 1.8.2: relation "auth_user" does not exist

### ISSUE THREAD

**Issue by kutenai** [pinax/django-user-accounts#179]
I updated my project from 1.7.x to 1.8.2, and tests failed with the above issue.
I've tried a number of solutions to fix this, and I did narrow it down to django-user-accounts. When I comment that project out, things work.

I reverted back to Django 1.7.6, and the tests work fine. I was unable to find any references to that error related to django-user-accounts, but I did find references related to other projects that seem to say that a migration is required. This project currently has no migrations. That is just a wild guess on my part..

This project claims support for Django 1.8, so I'm confused about why I'm getting this error, and others are not.

**Comment by john2x** [comment]
Getting the same issue as well with 1.8, although this is for a new project (no existing migrations, etc.).

**Comment by mattions** [comment]
If you create a project using django 1.8.2 `django.contrib.sites` is not automatically included in your installed app and it's a needed dependencies: http://django-user-accounts.readthedocs.org/en/latest/installation.html#django-contrib-sites

the fix is quick:
add `django.contrib.sites` to your INSTALLED_APPS

for reference:

```
INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites'
)

```

and run the migrate command

**Comment by john2x** [comment]
For my case, I already have `django.contrib.sites` in the project.

**Comment by mattions** [comment]
did you run `python manage.py migrate` ?
The table should be created by that.

**Comment by john2x** [comment]
ah running `python manage.py migrate` fails because of the `"account"` app, so I need to do `python manage.py migrate auth` first, which fails but is another issue with regards to `sites` app I guess.

**Comment by protactinium** [comment]
Any solution for this issue? I'm still having the same problem. Would be great to have a fix.

**Comment by brosner** [comment]
I will be looking at this issue today.

**Comment by ravigadila** [comment]
Hi, any body got solution? same problem for me.

$python manage.py migrate
   django.db.utils.ProgrammingError: relation "auth_user" does not exist
$python manage.py migrate auth
   django.db.utils.ProgrammingError: relation "django_site" does not exist
   LINE 1: SELECT (1) AS "a" FROM "django_site" LIMIT 1

**Comment by brosner** [comment]
@ravigadila can you post your `INSTALLED_APPS`?

**Comment by ravigadila** [comment]
@brosner 

INSTALLED_APPS = (
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.sites',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'djangocms_admin_style',
    'django.contrib.admin',
    'django_extensions',
    'django_model_changes',
    'django_messages',
    'userena',
    'guardian',
    'easy_thumbnails',
    'mathfilters',
    'crispy_forms',
    'accounts',
    'paypal.standard.ipn',
    'loans',
    'messaging',
    'rest_framework',
    'rest_framework.authtoken',
)

**Comment by brosner** [comment]
I am having a hard time reproducing this problem. What database are you using @ravigadila?

**Comment by rischanlab** [comment]
Hi @brosner Is there any body got the solution?. 
I got same problem and after I checked one by one by giving a comment in each apps and I found that the problem is the `accounts` application. 

this is my installed_app
```
'crispy_forms',
    'widget_tweaks',  # lets us add some bootstrap css to form elements
    'accounts',  # userena
    'guardian',  # for userena
    'easy_thumbnails',  # also needed for userena
    'userena',
    'raven.contrib.django',
    'reversion',
    'rosetta',
    'embed_video',
``` 

and still more, but as I told you before that when I giving a comments in each app the problem in accounts. I've change the order but I guess I have to put `accounts` app in the top. 

I use postgresql for the database. 

thank you

**Comment by alons45** [comment]
Same problem Postgresql database

**Comment by Amar-Chaudhari** [comment]
Kind of same problem -

  Applying admin.0001_initial...Traceback (most recent call last):
  File "/Users/amarchaudhari/Documents/gaurav_project/fit/lib/python3.4/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
psycopg2.ProgrammingError: relation "main_myuser" does not exist


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/amarchaudhari/Documents/gaurav_project/fit/lib/python3.4/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/Users/amarchaudhari/Documents/gaurav_project/fit/lib/python3.4/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/amarchaudhari/Documents/gaurav_project/fit/lib/python3.4/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/amarchaudhari/Documents/gaurav_project/fit/lib/python3.4/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/Users/amarchaudhari/Documents/gaurav_project/fit/lib/python3.4/site-packages/django/core/management/commands/migrate.py", line 222, in handle
    executor.migrate(targets, plan, fake=fake, fake_initial=fake_initial)
  File "/Users/amarchaudhari/Documents/gaurav_project/fit/lib/python3.4/site-packages/django/db/migrations/executor.py", line 110, in migrate
    self.apply_migration(states[migration], migration, fake=fake, fake_initial=fake_initial)
  File "/Users/amarchaudhari/Documents/gaurav_project/fit/lib/python3.4/site-packages/django/db/migrations/executor.py", line 148, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/Users/amarchaudhari/Documents/gaurav_project/fit/lib/python3.4/site-packages/django/db/backends/base/schema.py", line 91, in __exit__
    self.execute(sql)
  File "/Users/amarchaudhari/Documents/gaurav_project/fit/lib/python3.4/site-packages/django/db/backends/base/schema.py", line 111, in execute
    cursor.execute(sql, params)
  File "/Users/amarchaudhari/Documents/gaurav_project/fit/lib/python3.4/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/Users/amarchaudhari/Documents/gaurav_project/fit/lib/python3.4/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/Users/amarchaudhari/Documents/gaurav_project/fit/lib/python3.4/site-packages/django/db/utils.py", line 98, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/Users/amarchaudhari/Documents/gaurav_project/fit/lib/python3.4/site-packages/django/utils/six.py", line 658, in reraise
    raise value.with_traceback(tb)
  File "/Users/amarchaudhari/Documents/gaurav_project/fit/lib/python3.4/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "main_myuser" does not exist

**Comment by brosner** [comment]
I don't like how so many people have commented on this issue saying they have an issue, but I cannot reproduce it. I *really* want to find a fix for what's going on. If anyone has a project where this is easily reproducible, could you share it with me? I suspect there is something going on that is hidden in the project.

@john2x: you seem to be my only hope as you claim you can reproduce this with a fresh started project. Are you still able to reproduce this issue?

**Comment by jeymichael** [comment]
I narrowed this down to switching to postgres DB, at least in my case.   The project works on sqlite, but when switched to postgres, this error pops up.   This breaks the whole test /infrastructure process.

**Comment by brosner** [comment]
@jeymichael I have tested against both SQLite and PostgreSQL. Which version of PostgreSQL are you running?

**Comment by jeymichael** [comment]
Postgres 9.4.5.0

**Comment by jeymichael** [comment]
$ cat requirements.txt 
Django==1.8.6
djangorestframework==3.3.1
psycopg2==2.6.1
requests==2.8.1
wheel==0.24.0

**Comment by jeymichael** [comment]
Brian, I have the archived project as well, if you need it.

**Comment by brosner** [comment]
@jeymichael thanks for the info. I am going to start a project using those exact requirements and versions. I'll let you know if I need it.

**Comment by brosner** [comment]
@jeymichael are you on our Pinax Slack instance? It'd be really helpful for me if you joined the #django-user-accounts channel and we can talk there. http://slack.pinaxproject.com to join.

**Comment by leonardocintra** [comment]
This error also occurred in Django 1.9
I ran the following command and it worked
`$ ./manage.py migrate auth`

:+1:

**Comment by amitt001** [comment]
Getting the same error.

python manage.py makemigrations auth
>> No changes detected in app 'auth'

In [1]: from django.contrib.auth.models import User
In [2]: user = User.objects.create_user('test', 'test@test.com', 'testpass'
)

ProgrammingError: relation "auth_user" does not exist
LINE 1: INSERT INTO "auth_user" ("password", "last_login", "is_super...

**Comment by mwaz** [comment]
the error also persists in Django v.1.11 @brosner 
With the following installed apps

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.humanize',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

<img width="1440" alt="screen shot 2018-01-11 at 20 27 39" src="https://user-images.githubusercontent.com/10160787/34838103-f2cd5042-f70d-11e7-82e4-9a9f822283e0.png">

**Comment by heidihoge** [comment]
None of those commands resolved this issue (Django 2). I deleted my database and migrate again :/ , that's do worked haha

**Comment by Revel109** [comment]
`Just delete the existing data and create a new one, then try ./manage.py migrate`

**Comment by bazokizo** [comment]
@Revel109 ive done that and still getting this error when deploying to heroku

ProgrammingError at /
relation "posts_post" does not exist
LINE 1: ...evious_post_id", "posts_post"."next_post_id" FROM "posts_pos...
                                                             ^

**Comment by memetics19** [comment]
I think it's been appearing in the django-2.2 version also

**Comment by Bharath95** [comment]
I see it in django-3.0 as well, with postgres.

**Comment by ShashankJaitly** [comment]
hey, I have found the reason for this issue. It pops with `relation "auth_user" does not exist`
whenever we try to reference to `User` from `django.contrib.auth.models` before building our first auth migrations. So the solution for this that worked for  me was Commenting out any reference to the User model and then running the migrations, later you can uncomment User model references and run new migrations.

**Comment by memetics19** [comment]
@ShashankJaitly  I think, it's not a good practice to do it. DUA really resolved this issue in later stage but the django updated the version recently, May be it's not depreciated yet.

**Comment by ShashankJaitly** [comment]
@memetics19 Yes, you may right. But I recently got this issue while working on Django 3.0.6 and I managed to get through it just like I mentioned in my last comment, and it worked fine.

**Comment by rashabeka** [comment]
i got the same issu using cassandra (django version 4.1.7 )> Any suggestions ?

**Comment by uhurusurfa** [comment]
@rashabeka - make sure you have run all the migrations for the apps you are using
