### ISSUE TITLE
Compat not installed in DUA

### ISSUE THREAD

**Issue by afieldio** [pinax/django-user-accounts#191]
Traceback (most recent call last):
  File "./manage.py", line 12, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/adamf/.virtualenvs/ff/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/Users/adamf/.virtualenvs/ff/lib/python2.7/site-packages/django/core/management/__init__.py", line 312, in execute
    django.setup()
  File "/Users/adamf/.virtualenvs/ff/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/adamf/.virtualenvs/ff/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/Users/adamf/.virtualenvs/ff/lib/python2.7/site-packages/django/apps/config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/adamf/.virtualenvs/ff/lib/python2.7/site-packages/pinax/teams/models.py", line 12, in <module>
    from account.compat import AUTH_USER_MODEL
ImportError: No module named compat
(ff)Adams-MacBook-Air:ff adamf$ ./manage.py runserver
Traceback (most recent call last):
  File "./manage.py", line 12, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/adamf/.virtualenvs/ff/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/Users/adamf/.virtualenvs/ff/lib/python2.7/site-packages/django/core/management/__init__.py", line 312, in execute
    django.setup()
  File "/Users/adamf/.virtualenvs/ff/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/adamf/.virtualenvs/ff/lib/python2.7/site-packages/django/apps/registry.py", line 89, in populate
    "duplicates: %s" % app_config.label)
django.core.exceptions.ImproperlyConfigured: Application labels aren't unique, duplicates: account
(ff)Adams-MacBook-Air:ff adamf$ ./manage.py runserver
Traceback (most recent call last):
  File "./manage.py", line 12, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/adamf/.virtualenvs/ff/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/Users/adamf/.virtualenvs/ff/lib/python2.7/site-packages/django/core/management/__init__.py", line 312, in execute
    django.setup()
  File "/Users/adamf/.virtualenvs/ff/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/adamf/.virtualenvs/ff/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/Users/adamf/.virtualenvs/ff/lib/python2.7/site-packages/django/apps/config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/adamf/.virtualenvs/ff/lib/python2.7/site-packages/pinax/teams/models.py", line 12, in <module>
    from account.compat import AUTH_USER_MODEL
ImportError: No module named compat
(ff)Adams-MacBook-Air:ff adamf$ ./manage.py migrate
Traceback (most recent call last):
  File "./manage.py", line 12, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/adamf/.virtualenvs/ff/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/Users/adamf/.virtualenvs/ff/lib/python2.7/site-packages/django/core/management/__init__.py", line 312, in execute
    django.setup()
  File "/Users/adamf/.virtualenvs/ff/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/adamf/.virtualenvs/ff/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/Users/adamf/.virtualenvs/ff/lib/python2.7/site-packages/django/apps/config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/adamf/.virtualenvs/ff/lib/python2.7/site-packages/pinax/teams/models.py", line 12, in <module>
    from account.compat import AUTH_USER_MODEL
ImportError: No module named compat

**Comment by brosner** [comment]
What version of django-user-accounts do you have installed?
