### ISSUE TITLE
why ?OperationalError: no such table: auth_user?

### ISSUE THREAD

**Issue by gogobody** [pinax/django-user-accounts#221]
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 123, in get_response
    response = middleware_method(request)
  File "D:\discriminate\account\middleware.py", line 29, in process_request
    translation.activate(self.get_language_for_user(request))
  File "D:\discriminate\account\middleware.py", line 20, in get_language_for_user
    if request.user.is_authenticated():
  File "C:\Python27\lib\site-packages\django\utils\functional.py", line 204, in inner
    self._setup()
  File "C:\Python27\lib\site-packages\django\utils\functional.py", line 351, in _setup
    self._wrapped = self._setupfunc()
  File "C:\Python27\lib\site-packages\django\contrib\auth\middleware.py", line 22, in <lambda>
    request.user = SimpleLazyObject(lambda: get_user(request))
  File "C:\Python27\lib\site-packages\django\contrib\auth\middleware.py", line 10, in get_user
    request._cached_user = auth.get_user(request)
  File "C:\Python27\lib\site-packages\django\contrib\auth__init__.py", line 174, in get_user
    user = backend.get_user(user_id)
  File "C:\Python27\lib\site-packages\django\contrib\auth\backends.py", line 93, in get_user
    return UserModel._default_manager.get(pk=user_id)
  File "C:\Python27\lib\site-packages\django\db\models\manager.py", line 122, in manager_method
    return getattr(self.get_queryset(), name)(_args, *_kwargs)
  File "C:\Python27\lib\site-packages\django\db\models\query.py", line 381, in get
    num = len(clone)
  File "C:\Python27\lib\site-packages\django\db\models\query.py", line 240, in __len__
    self._fetch_all()
  File "C:\Python27\lib\site-packages\django\db\models\query.py", line 1074, in _fetch_all
    self._result_cache = list(self.iterator())
  File "C:\Python27\lib\site-packages\django\db\models\query.py", line 52, in __iter__
    results = compiler.execute_sql()
  File "C:\Python27\lib\site-packages\django\db\models\sql\compiler.py", line 848, in execute_sql
    cursor.execute(sql, params)
  File "C:\Python27\lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "C:\Python27\lib\site-packages\django\db\backends\utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "C:\Python27\lib\site-packages\django\db\utils.py", line 95, in **exit**
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "C:\Python27\lib\site-packages\django\db\backends\utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "C:\Python27\lib\site-packages\django\db\backends\sqlite3\base.py", line 323, in execute
    return Database.Cursor.execute(self, query, params)
OperationalError: no such table: auth_user

how to solve this problem?plz

**Comment by ossanna16** [comment]
@brosner Can you help with this?

**Comment by rakeshk414** [comment]
Two possibilities are there
1. First you not defined user in your models  
    from django.utils import timezone
 user = models.ForeignKey('auth.User', on_delete=models.CASCADE)
2. If  you added these code in models, But you not done -> makemigrations & migrate
  Try this once.

If it works means do this by cross check in python shell
>>> from django.contrib.auth.models import User
>>>user = User.objects.create_user('rakesh', 'rakesh@gmail.com', 'admin@123')
>>> user = User.objects.get(id=1)
>>> print user

**Comment by mamunarch** [comment]
https://stackoverflow.com/questions/53637182/django-no-such-table-main-auth-user-old
follow this

**Comment by KatherineMichel** [comment]
@paltman @brosner Getting same error when working on porting pinax-notifications from Python 2 to 3. Not sure yet, but wondering if DUA might need to be updated as well, otherwise will be a blocker as far as tox is concerned. This line in particular seems to be a problem atm. https://github.com/pinax/django-user-accounts/blob/master/account/models.py#L12

**Comment by cjekin** [comment]
Won't be applicable to everyone, but I was doing this in PyCharm and had my working directory set incorrectly.
