### ISSUE TITLE
sqlite3.OperationalError: no such table: account_passwordhistory

### ISSUE THREAD

**Issue by cegg** [pinax/django-user-accounts#300]
Installed django-user-accounts:

```
$ pip install django-user-accounts
Collecting django-user-accounts
  Downloading https://files.pythonhosted.org/packages/0c/4f/40f76395324d98b7f8717aad7e08ad6f86ba2714eb956be6070e0402988c/django_user_accounts-2.0.3-py2.py3-none-any.whl (106kB)
    100% |████████████████████████████████| 112kB 2.8MB/s
.
.
.
Installing collected packages: django-appconf, django-user-accounts
Successfully installed django-appconf-1.0.2 django-user-accounts-2.0.3
```

in settings.py added 

```
INSTALLED_APPS = [
.
.
.
    'django.contrib.sites',
    'account'
]

SITE_ID = 1

MIDDLEWARE = [
.
.
.
    'account.middleware.ExpiredPasswordMiddleware',
]

ACCOUNT_PASSWORD_USE_HISTORY = True
ACCOUNT_PASSWORD_EXPIRY = 60  # number of seconds
```

restarted server and ran : `$ python manage.py user_password_history`
Got:
Traceback (most recent call last):
  File "/Users/ipozdnya/miniconda3/lib/python3.5/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/Users/someuser/miniconda3/lib/python3.5/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such table: account_passwordhistory

I realize that account_passwordhistory did not get created at the time of install or some othr stem, but nothing in this doc tells me what to do about it: http://blog.pinaxproject.com/2016/11/22/how-configure-password-expiration-for-your-site/

Thanks. Igor

**Comment by cegg** [comment]
Ok, my problem was that I trusted the output of `$ python manage.py makemigrations`
that stated that `No changes detected`. However, when I did run $ python manage.py migrate, it applied a new migration for account_passwordhistory and account_passwordexpire tables just fine:

    Applying account.0003_passwordexpiry_passwordhistory... OK

And the tables are in the DB. 

Setting my password to expire in 1 second (`python manage.py user_password_expiry my_user_name --expire 1`) however dod not have any effect on the site functionality, but that's a different issue.
