### ISSUE TITLE
ImportError: cannot import name 'six' from 'django.utils' in django 3.0

### ISSUE THREAD

**Issue by memetics19** [pinax/django-user-accounts#326]
` py manage.py migrate 
Traceback (most recent call last):
  File "manage.py", line 12, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Users\Shreeda\documents\work\venv\lib\site-packages\django\core\management\__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "C:\Users\Shreeda\documents\work\venv\lib\site-packages\django\core\management\__init__.py", line 377, in execute
    django.setup()
  File "C:\Users\Shreeda\documents\work\venv\lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Users\Shreeda\documents\work\venv\lib\site-packages\django\apps\registry.py", line 114, in populate
    app_config.import_models()
  File "C:\Users\Shreeda\documents\work\venv\lib\site-packages\django\apps\config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "C:\Users\Shreeda\documents\work\venv\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\Shreeda\documents\work\venv\lib\site-packages\account\models.py", line 15, in <module>
    from django.utils import timezone, translation, six
ImportError: cannot import name 'six' from 'django.utils' (C:\Users\Shreeda\documents\work\venv\lib\site-packages\django\utils\__init__.py)
(venv) `

there is a bug in pinax account package.

**Comment by KatherineMichel** [comment]
@memetics19, are you using an older version of DUA? six was dropped in the most recent release. Previous releases didn't support Django 3.0. https://github.com/pinax/django-user-accounts/pull/322/files

**Comment by memetics19** [comment]
i'm using this version 
django-user-accounts==2.0.3

**Comment by avanish24** [comment]
@KatherineMichel the issue is when you do a `pinax start account yourapp` this doesn't fetches the account data from the latest changes, probably need to fix that.

**Comment by KatherineMichel** [comment]
@avanish24 I think it's because the versions haven't been updated in the `distributions.json` file. The pinax-cli uses the info in these two files when it's creating a project. DUA will be added as part of the new release. It's in process though. We don't actually have a release version number atm.
https://github.com/pinax/pinax-cli/blob/master/pinaxcli/cli.py
https://github.com/pinax/pinax/blob/master/projects.json
https://github.com/pinax/pinax/blob/master/distributions.json
